// GENERATED by scripts/build-islands.mjs from source/character-builder/index.html. Do not edit by hand.
/* eslint-disable */
// @ts-nocheck
import { esc, sgn, ABS, SKILLS } from './character';

const od=n=>n; const step=(L,pairs)=>{ let v=pairs[0][1]; pairs.forEach(([l,x])=>{ if(L>=l) v=x; }); return v; };

// Rules rows store functions as {"$fn": "source"}. Only the DM can write rules rows.
export function revive(v){
  if(Array.isArray(v)) return v.map(revive);
  if(v&&typeof v==='object'){ if(typeof v.$fn==='string') return new Function('step','sgn','return ('+v.$fn+')')(step,sgn); const o={}; for(const k in v) o[k]=revive(v[k]); return o; }
  return v;
}

export function mountBuilder(root, opts){
const $=s=>root.querySelector(s);
const ABN=Object.fromEntries(ABS);
const ALLSK=SKILLS.map(s=>s[0]);
const amod=v=>Math.floor((v-10)/2);
const {RACES,CLASSES,FULL,PACT,ORD,BGS,ARMOR,WEAPONS,SPELLS,ANCESTRY,TIME,COST,ARRAY}=revive(opts.rules);
const CFG=opts.phaseConfig||{};
const SPBY=Object.fromEntries(SPELLS.map(x=>[x.n,x]));

/* ---------- state ---------- */
const blank=()=>({race:'',p2:'',p1:'',anc:'',cls:'',sub:'',level:0,method:'array',base:{str:15,dex:14,con:13,int:12,wis:10,cha:8},asi:{str:0,dex:0,con:0,int:0,wis:0,cha:0},featN:0,bg:'',bgSk:[],clsSk:[],raceSk:[],exp:[],picked:[],armor:'None',shield:false,w:['','',''],gear:'',cantrips:'',spells:'',extras:'',name:'',player:'',langs:'',look:'',story:'',card:{go:'',sig:'',emg:''}});
let S=blank(), PHASE=opts.phase==='after'?'after':'before', step_=0;
try{ const o=opts.state; if(o){ S=Object.assign(blank(),o); S.base=Object.assign(blank().base,o.base||{}); S.asi=Object.assign(blank().asi,o.asi||{}); S.card=Object.assign(blank().card,o.card||{}); ['bgSk','clsSk','raceSk','exp','w','picked'].forEach(k=>{ if(!Array.isArray(S[k])) S[k]=blank()[k]; }); } }catch(e){ S=blank(); }
function persist(){ opts.persist(S); }
const race=()=>RACES.find(r=>r.id===S.race);
const cls=()=>CLASSES.find(c=>c.id===S.cls);
const lvl=()=>Math.max(1,Math.min(20,parseInt(S.level,10)||(CFG.defaultLevel||1)));
const lineOf=r=>Array.isArray(r.line)?r.line[PHASE==='after'?1:0]:r.line;
function asiCount(){ const c=cls(), L=lvl(); if(!c) return 0; let ls=[4,8,12,16,19]; if(c.id==='fighter') ls=ls.concat([6,14]); if(c.id==='rogue') ls=ls.concat([10]); return ls.filter(x=>L>=x).length; }

/* ---------- the maths ---------- */
function calc(){
  const r=race(), c=cls(), L=lvl(), pb=2+Math.floor((L-1)/4), D={L,pb,ab:{},m:{}};
  ABS.forEach(([k])=>{ let v=(parseInt(S.base[k],10)||8)+(S.p2===k?2:0)+(S.p1===k?1:0)+(parseInt(S.asi[k],10)||0); let cap=20;
    if(c&&c.id==='barbarian'&&L>=20&&(k==='str'||k==='con')){ v+=4; cap=24; }
    D.ab[k]=Math.min(cap,v); D.m[k]=amod(D.ab[k]); });
  D.saves={}; ABS.forEach(([k])=>{ D.saves[k]=!!(c&&(c.saves.includes(k)||(c.id==='monk'&&L>=14)||(c.id==='rogue'&&L>=15&&k==='wis'))); });
  const bg=BGS.find(b=>b[0]===S.bg); D.bgSk=bg?(bg[0]==='Custom'?S.bgSk.slice(0,2):bg[1]):[];
  D.prof={}; D.bgSk.concat(S.clsSk,S.raceSk).forEach(s=>{ D.prof[s]=1; }); S.exp.forEach(s=>{ if(D.prof[s]) D.prof[s]=2; });
  D.skill=n=>{ const a=SKILLS.find(s=>s[0]===n)[1]; return D.m[a]+pb*(D.prof[n]||0); };
  /* hit points */
  const hd=c?c.hd:8;
  D.hp=Math.max(1,hd+D.m.con)+(L-1)*Math.max(1,hd/2+1+D.m.con)+(CFG.vitality?Math.floor(D.ab.con/2):0);
  D.hd=L+'d'+hd;
  /* armor class */
  const ar=ARMOR.find(a=>a[0]===S.armor)||ARMOR[0], sh=S.shield?2:0; let ac, acNote;
  if(r&&r.id==='tortle'){ ac=17+sh; acNote='Natural armor'; }
  else if(ar[1]!=='none'){ ac=ar[2]+Math.min(D.m.dex,ar[3])+sh; acNote=ar[0]+(sh?' and shield':''); }
  else { const opts=[[10+D.m.dex+sh,'Unarmored'+(sh?' with shield':'')]];
    if(r&&r.id==='corrin') opts.push([13+D.m.dex+sh,'Stone body'+(sh?' with shield':'')]);
    if(c&&c.id==='barbarian') opts.push([10+D.m.dex+D.m.con+sh,'Unarmored Defense'+(sh?' with shield':'')]);
    if(c&&c.id==='monk'&&!sh) opts.push([10+D.m.dex+D.m.wis,'Unarmored Defense']);
    if(c&&c.id==='avenger'&&!sh) opts.push([10+D.m.dex+D.m.wis,'Armor of Faith']);
    if(c&&c.id==='warden') opts.push([10+D.m.dex+D.m.con+sh,'Guardian\'s Hide'+(sh?' with shield':'')]);
    opts.sort((a,b)=>b[0]-a[0]); ac=opts[0][0]; acNote=opts[0][1]; }
  if(c&&c.id==='swordmage'&&!sh&&!(r&&r.id==='tortle')){ ac+=L>=11?2:1; acNote+=', Swordmage Warding'; }
  D.ac=ac; D.acNote=acNote;
  /* speed */
  let walk=r?r.walk:30; const bare=ar[1]==='none';
  if(c&&c.id==='barbarian'&&L>=5&&ar[1]!=='heavy') walk+=10;
  if(c&&c.id==='monk'&&L>=2&&bare&&!S.shield) walk+=step(L,[[2,10],[6,15],[10,20],[14,25],[18,30]]);
  const sp=[walk+' ft']; if(r){ if(r.swim) sp.push('swim '+r.swim+' ft'); if(r.climb) sp.push('climb '+r.climb+' ft');
    if(r.id==='aarakocra'&&L>=2&&ar[1]!=='medium'&&ar[1]!=='heavy') sp.push('fly '+(L>=7?50:30)+' ft'); }
  D.speed=sp.join(', ');
  D.atk=!c?1:c.id==='fighter'?step(L,[[1,1],[5,2],[11,3],[20,4]]):(['barbarian','monk','paladin','ranger','warlord','swordmage','avenger','warden'].includes(c.id)&&L>=5?2:1);
  /* spellcasting */
  if(c&&c.cast&&!(c.cast.type==='half'&&L<2)){ const k=c.cast.ab, sc={ab:k,dc:8+pb+D.m[k],atk:pb+D.m[k]};
    if(c.cast.type==='pact'){ const p=PACT[L-1]; sc.slots=p[0]+' pact slot'+(p[0]>1?'s':'')+' of '+ORD[p[1]]+' level, back on a short rest'; }
    else { const eff=c.cast.type==='full'?L:Math.ceil(L/2); sc.slots=FULL[eff-1].map((n,i)=>ORD[i+1]+': '+n).join(', '); }
    if(c.cast.can) sc.can=step(L,c.cast.can);
    if(c.cast.prep) sc.count='Prepare '+Math.max(1,D.m[k]+(c.cast.prep==='full'?L:Math.floor(L/2)))+' spells each day';
    else if(c.cast.known) sc.count='You know '+c.cast.known[L-1]+' spells';
    sc.list=c.cast.list; sc.max=c.cast.type==='pact'?Math.min(9,Math.ceil(L/2)):FULL[(c.cast.type==='full'?L:Math.ceil(L/2))-1].length;
    D.cast=sc; }
  /* attacks */
  D.attacks=[];
  const add=(name,die,type,ab,prof,note)=>{ const m=D.m[ab]; D.attacks.push({name,roll:sgn(m+(prof?pb:0))+' to hit, '+die+(m?sgn(m):'')+' '+type,desc:(note?note+'. ':'')+(prof?'':'Not proficient. ')+'Uses '+ABN[ab]+'.'}); };
  const best=()=>D.m.dex>D.m.str?'dex':'str';
  S.w.forEach(n=>{ const w=WEAPONS.find(x=>x[0]===n); if(!w) return; const f=w[4]; const ab=f.includes('r')&&!f.includes('f')?'dex':f.includes('f')?best():(c&&c.id==='monk'&&(w[1]==='simple'||w[0]==='Shortsword')&&!/Two-handed|Heavy/.test(w[5])?best():'str');
    const prof=!!(c&&(c.weap.includes(w[1])||c.weap.includes(w[0]))); add(w[0],w[2],w[3],ab,prof,w[5]); });
  if(r&&r.nat) add(r.nat.name,r.nat.die,r.nat.type,r.nat.fin||(c&&c.id==='monk')?best():'str',true,'Natural weapon');
  if(c&&c.id==='monk') add('Unarmed strike','1d'+step(L,[[1,4],[5,6],[11,8],[17,10]]),'bludgeoning',best(),true,'Martial Arts');
  /* skill pick limits */
  D.nCls=c?c.n:0; D.nRace=r&&r.picks?r.picks.n:0;
  D.nExp=(c&&c.id==='rogue'?(L>=6?4:2):0)+(c&&c.id==='bard'?(L>=10?4:L>=3?2:0):0)+(r&&r.id==='human'&&L>=7?1:0);
  D.asiBudget=Math.max(0,2*(asiCount()-(parseInt(S.featN,10)||0)));
  D.asiSpent=ABS.reduce((t,[k])=>t+(parseInt(S.asi[k],10)||0),0);
  return D;
}

/* what the player guide's My character page stores */
function toHub(){
  const D=calc(), r=race(), c=cls(), L=D.L, opts=[]; let n=0;
  const push=(cat,name,cost,roll,max,desc)=>opts.push({id:'b'+(n++).toString(36)+Date.now().toString(36).slice(-4),cat,name,cost:cost||'Passive',roll:roll||'',max:Math.max(0,Math.min(12,max||0)),used:0,desc:desc||''});
  D.attacks.forEach(a=>push('Attack',a.name,'Action',a.roll,0,a.desc));
  if(r){ r.traits.forEach(t=>{ const o=t[2]||{}; if(o.min&&L<o.min) return;
      push('Ability',t[0],o.cost,o.roll?o.roll(L,D.pb,D):'',o.uses==='pb'?D.pb:(o.uses||0),t[1]+(PHASE==='after'&&o.after?o.after:'')+(t[0]==='Ancestry'&&S.anc?' Yours: '+S.anc+'.':'')); });
    if(L>=(r.upLvl||7)) push('Ability',r.name+' level '+(r.upLvl||7)+' upgrade','Passive','',0,r.up); }
  if(c){ c.feats.forEach(f=>{ if(L<f[0]) return; const txt=typeof f[3]==='function'?f[3](L,D):f[3]; const uses=typeof f[4]==='function'?f[4](L,D):(f[4]||0);
      push('Ability',f[1],f[2],f[5]?f[5](L,D):'',uses,txt); });
    if(D.atk>1) push('Ability','Extra Attack','Passive','',0,'You attack '+D.atk+' times whenever you take the Attack action.'); }
  if(D.cast) push('Spell','Spellcasting ('+ABN[D.cast.ab]+')','Passive','Save DC '+D.cast.dc+', '+sgn(D.cast.atk)+' to hit',0,'Slots: '+D.cast.slots+'.'+(D.cast.can?' Cantrips known: '+D.cast.can+'.':'')+(D.cast.count?' '+D.cast.count+'.':''));
  const lines=t=>String(t||'').split('\n').map(x=>x.trim()).filter(Boolean);
  const split=x=>{ const i=x.indexOf(':'); return i>0?[x.slice(0,i).trim(),x.slice(i+1).trim()]:[x,'']; };
  S.picked.map(n=>SPBY[n]).filter(Boolean).sort((a,b)=>a.l-b.l||a.n.localeCompare(b.n)).forEach(x=>push('Spell',x.n,TIME[x.t]||'Action',(x.l?ORD[x.l]+' level':'Cantrip')+(x.f.includes('c')?', concentration':'')+(x.f.includes('r')?', ritual':'')+(TIME[x.t]?'':', casting time '+x.t),0,x.d));
  lines(S.cantrips).forEach(x=>{ const [a,b]=split(x); push('Spell',a,'Action','Cantrip',0,b); });
  lines(S.spells).forEach(x=>{ const [a,b]=split(x); push('Spell',a,'Action','',0,b); });
  lines(S.extras).forEach(x=>{ const [a,b]=split(x); push('Ability',a,'Passive','',0,b); });
  const sk={}; Object.keys(D.prof).forEach(k=>{ sk[k]=D.prof[k]; });
  const notes=[S.bg?'Background: '+S.bg:'', c?'Armor: '+c.armor+'. Weapons: '+c.weap.map(w=>w==='simple'?'simple weapons':w==='martial'?'martial weapons':w.toLowerCase()).join(', ')+'.':'', S.langs?'Languages: '+S.langs:'', D.cast?'Spell slots: '+D.cast.slots:'', S.look?'Appearance: '+S.look:'', S.story?'Story: '+S.story:''].filter(Boolean).join('\n\n');
  const gear=[S.armor!=='None'?S.armor:'', S.shield?'Shield':''].concat(S.w.filter(Boolean)).filter(Boolean).join(', ')+(S.gear?(S.armor!=='None'||S.shield||S.w.some(Boolean)?'\n':'')+S.gear:'');
  return {t:Date.now(),name:S.name,player:S.player,race:S.race,cls:c?c.name+(S.sub?' ('+S.sub+')':''):'',level:L,domain:'',tier:'',spark:'',faith:'',ab:D.ab,sv:D.saves,sk,ac:D.ac,hpMax:D.hp,hp:D.hp,temp:0,speed:D.speed,hd:D.hd,acts:1,bonus:1,react:1,atk:D.atk,card:S.card,options:opts,gear,notes};
}
const encode=o=>'TBG1:'+btoa(unescape(encodeURIComponent(JSON.stringify(o))));

/* ---------- steps ---------- */
const STEPS=[['race','People'],['class','Class'],['abil','Abilities'],['skills','Skills'],['gear','Gear'],['spells','Spells'],['details','Details'],['sheet','Sheet'],['combat','Combat']];
function doneFlags(){ const D=calc(); return [!!S.race&&!!S.p2&&!!S.p1, !!S.cls, true, !!S.bg&&S.clsSk.length===D.nCls&&S.raceSk.length===D.nRace, true, true, !!S.name, false, false]; }
function renderTabs(){ const d=doneFlags(), bar=$('#tabs');
  if(!bar.children.length) bar.innerHTML=STEPS.map((s,i)=>`<button class="tab" role="tab" data-step="${i}">${s[1]}</button>`).join('');
  Array.from(bar.children).forEach((b,i)=>{ b.classList.toggle('done',!!d[i]); b.setAttribute('aria-selected',i===step_); }); }
function go(i){ step_=Math.max(0,Math.min(STEPS.length-1,i)); STEPS.forEach((s,j)=>{ $('#p-'+s[0]).hidden=j!==step_; });
  try{ sessionStorage.setItem('dbb-builder-step',String(step_)); }catch(e){}
  render(); $('#prev').hidden=step_===0; $('#next').hidden=step_===STEPS.length-1; $('#next').textContent=step_===6?'See my sheet':step_===7?'See my combat page':'Next';
  const v=$('#rv'); if(step_===0) playVid(); else v.pause(); }
function render(){ renderTabs(); [renderRace,renderClass,renderAbil,renderSkills,renderGear,renderSpells,renderDetails,renderSheet,renderCombat][step_](); }
const sel=(key,opts,val,ph)=>`<select data-s="${key}" id="f-${key.replace(/\./g,'-')}">${ph?`<option value="">${ph}</option>`:''}${opts.map(o=>{ const v=Array.isArray(o)?o[0]:o, t=Array.isArray(o)?o[1]:o; return `<option value="${esc(v)}"${String(v)===String(val)?' selected':''}>${esc(t)}</option>`; }).join('')}</select>`;

/* people */
let vidKey='';
function playVid(){ const r=race(), v=$('#rv'); if(!r){ return; }
  const base=opts.media+'/v/'+r.vid; if(vidKey!==base){ vidKey=base; v.poster=base+'.jpg'; v.src=base+'.mp4'; v.load(); }
  $('#rvHint').hidden=true; $('#rvBtn').hidden=false;
  if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){ $('#rvBtn').textContent='Play'; return; }
  const p=v.play(); if(p&&p.catch) p.catch(()=>{ $('#rvBtn').textContent='Play'; }); $('#rvBtn').textContent='Pause'; }
function renderRace(){
  $('#rail').innerHTML=RACES.map(r=>`<button class="rc" data-race="${r.id}" aria-pressed="${r.id===S.race}"><img src="${opts.media}/t/${r.vid}.jpg" alt="" loading="lazy" width="200" height="240"><span>${r.name}</span></button>`).join('');
  const r=race(); if(!r){ $('#raceInfo').innerHTML=''; return; }
  const L=lvl();
  $('#raceInfo').innerHTML=`<div class="plate"><h2 style="margin-top:0">${r.name}</h2><p class="lede">${esc(lineOf(r))}</p>
    <p class="who">${r.size}. Speed ${r.walk} ft${r.swim?', swim '+r.swim+' ft':''}${r.climb?', climb '+r.climb+' ft':''}${r.id==='aarakocra'?', fly 30 ft from level 2':''}.</p>
    <h4>Your choices</h4>
    <div class="fields">
      <label class="f">+2 to one ability${sel('p2',ABS,S.p2,'Choose')}</label>
      <label class="f">+1 to a different ability${sel('p1',ABS.filter(a=>a[0]!==S.p2),S.p1,'Choose')}</label>
      ${r.id==='dragonborn'?`<label class="f">Ancestry damage type${sel('anc',ANCESTRY,S.anc,'Choose')}</label>`:''}
    </div>
    ${r.picks?`<p class="who" style="margin-top:10px">You also pick ${r.picks.n} skill${r.picks.n>1?'s':''} from this people on the Skills step.</p>`:''}
  </div>
  <details open><summary>Full trait rules</summary><ul class="traits">
    ${r.traits.map(t=>`<li><b>${esc(t[0])}.</b> ${esc(t[1]+(PHASE==='after'&&t[2]&&t[2].after?t[2].after:''))}</li>`).join('')}
    <li><b>Level ${r.upLvl||7}.</b> ${esc(r.up)}</li></ul></details>`;
}

/* class */
function renderClass(){
  const c=cls(), L=lvl();
  let h=`<p class="lede">Choose a class and level.</p>
  <div class="plate"><div class="fields"><label class="f">Level${sel('level',Array.from({length:20},(_,i)=>i+1),L)}</label></div>
  <p class="who" style="margin-top:8px">${esc(CFG.levelNote||'')} Proficiency bonus ${sgn(2+Math.floor((L-1)/4))}.</p></div>
  <div class="cards" style="margin-top:16px">${CLASSES.map(x=>`<button class="cc" data-cls="${x.id}" aria-pressed="${x.id===S.cls}"><b>${x.name}</b><small>${x.src?'<span class="tag">'+x.src+'</span> ':''}d${x.hd} hit die. ${x.prim}.</small></button>`).join('')}</div>`;
  if(c){ const feats=c.feats.filter(f=>f[0]<=L), D=calc();
    h+=`<div class="grid g2" style="margin-top:16px"><div class="plate"><h3>${c.name}</h3>
      ${c.src?`<p class="who"><span class="tag">Converted from ${c.src}</span> ${esc(c.conv)} Your DM can adjust it.</p>`:''}
      <p class="who">Hit die d${c.hd}. Saving throws: ${c.saves.map(k=>ABN[k]).join(' and ')}.</p>
      <p class="who">Armor: ${c.armor}. Weapons: ${c.weap.map(w=>w==='simple'?'simple weapons':w==='martial'?'martial weapons':w.toLowerCase()).join(', ')}.</p>
      <p class="who">${c.cast?'Casts spells with '+ABN[c.cast.ab]+'.':'No spellcasting from the class itself.'}</p>
      ${L>=c.subAt?`<label class="f">${c.subName}<input data-s="sub" id="f-sub" list="subs" value="${esc(S.sub)}" autocomplete="off" placeholder="Choose or type your own"></label><datalist id="subs">${c.subs.map(s=>`<option value="${esc(s)}">`).join('')}</datalist>
      <p class="who" style="margin-top:8px">This builder lists the base class features. Add your ${c.subName.toLowerCase()} features on the Details step.</p>`:`<p class="who">You choose a ${c.subName.toLowerCase()} at level ${c.subAt}.</p>`}
    </div><div class="plate"><h3>Features at level ${L}</h3><ul class="traits">
      ${feats.map(f=>`<li><b>${esc(f[1])}</b> <span class="who">level ${f[0]}</span><br><span class="who">${esc(typeof f[3]==='function'?f[3](L,D):f[3])}</span></li>`).join('')}
      ${D.atk>1?`<li><b>Extra Attack</b><br><span class="who">You attack ${D.atk} times whenever you take the Attack action.</span></li>`:''}
      ${asiCount()?`<li><b>Ability Score Improvement</b><br><span class="who">${asiCount()} so far. Spend them on the Abilities step.</span></li>`:''}
    </ul></div></div>`; }
  $('#p-class').innerHTML=h;
}

/* abilities */
function renderAbil(){
  const D=calc(), r=race();
  const pts=ABS.reduce((t,[k])=>t+(COST[S.base[k]]==null?99:COST[S.base[k]]),0);
  const used={}; ABS.forEach(([k])=>{ used[S.base[k]]=(used[S.base[k]]||0)+1; });
  const dup=S.method==='array'&&ARRAY.some(v=>used[v]!==1);
  let h=`<p class="lede">Set your six ability scores.</p>
  <div class="plate"><div class="chips">${[['array','Standard array'],['buy','Point buy'],['manual','Rolled or custom']].map(m=>`<button class="chip" data-method="${m[0]}" aria-pressed="${S.method===m[0]}">${m[1]}</button>`).join('')}</div>
  <p class="who">${S.method==='array'?'Assign 15, 14, 13, 12, 10, and 8, one to each ability.'+(dup?' <span class="count bad">Each number should be used once.</span>':''):S.method==='buy'?`27 points to spend. Scores run from 8 to 15. <span class="count${pts>27?' bad':''}">${pts} of 27 spent.</span>`:'Type in the scores you rolled, or the ones your DM gave you.'}</p></div>
  <div class="abil" style="margin-top:16px">${ABS.map(([k,n])=>{ const bonus=(S.p2===k?2:0)+(S.p1===k?1:0);
    const input=S.method==='manual'?`<input type="number" min="3" max="18" data-s="base.${k}" data-num id="f-base-${k}" value="${esc(S.base[k])}">`:sel('base.'+k,S.method==='array'?ARRAY:[8,9,10,11,12,13,14,15],S.base[k]);
    return `<div class="ab"><label class="f">${n}${input}</label>
      <div class="tot">${D.ab[k]}<small>${sgn(D.m[k])}</small></div>
      <div class="parts">${bonus?'People +'+bonus+'. ':''}${D.asiBudget||S.asi[k]?`<label>Level-ups <input type="number" min="0" max="12" data-s="asi.${k}" data-num id="f-asi-${k}" value="${esc(S.asi[k]||0)}" style="width:64px;padding:2px 6px"></label>`:''}</div></div>`; }).join('')}</div>`;
  if(asiCount()) h+=`<div class="plate" style="margin-top:16px"><h3>Ability Score Improvements</h3>
    <p class="who">Your class has given you ${asiCount()} so far. Each is worth 2 points to add to your scores above (maximum 20), or you can trade one for a feat.</p>
    <div class="fields"><label class="f">Improvements traded for feats<input type="number" min="0" max="${asiCount()}" data-s="featN" data-num id="f-featN" value="${esc(S.featN||0)}"></label></div>
    <p class="count${D.asiSpent>D.asiBudget?' bad':''}" style="margin-top:8px">${D.asiSpent} of ${D.asiBudget} points placed.${(parseInt(S.featN,10)||0)?' Write your feats on the Details step.':''}</p></div>`;
  if(!r||!S.p2||!S.p1) h+=`<p class="warn">Your people give +2 to one ability and +1 to another. Choose them on the People step.</p>`;
  $('#p-abil').innerHTML=h;
}

/* skills */
function renderSkills(){
  const D=calc(), c=cls(), r=race(), taken=new Set(D.bgSk.concat(S.clsSk,S.raceSk));
  const group=(key,list,max,sel_)=>`<div class="chips">${list.map(s=>{ const on=sel_.includes(s), blocked=!on&&(taken.has(s)||sel_.length>=max); return `<button class="chip" data-pick="${key}" data-v="${esc(s)}" aria-pressed="${on}"${blocked?' disabled':''}>${esc(s)}</button>`; }).join('')}</div><p class="count${sel_.length!==max?' bad':''}">${sel_.length} of ${max} chosen.</p>`;
  let h=`<p class="lede">Choose a background and the skills you are trained in.</p>
  <div class="plate"><h3>Background</h3><div class="fields"><label class="f">Background${sel('bg',BGS.map(b=>b[0]),S.bg,'Choose')}</label></div>
  ${S.bg==='Custom'?`<p class="who" style="margin-top:10px">Pick any two skills.</p>${group('bgSk',ALLSK,2,S.bgSk)}`:S.bg?`<div class="chips">${D.bgSk.map(s=>`<span class="chip lock">${esc(s)}</span>`).join('')}</div>`:''}</div>`;
  h+=`<div class="plate" style="margin-top:16px"><h3>Class skills</h3>${c?`<p class="who">${c.name}: choose ${c.n}.</p>${group('clsSk',c.skills==='any'?ALLSK:c.skills,c.n,S.clsSk)}`:'<p class="who">Choose a class first.</p>'}</div>`;
  if(r&&r.picks) h+=`<div class="plate" style="margin-top:16px"><h3>${r.name} skills</h3><p class="who">Choose ${r.picks.n}.</p>${group('raceSk',r.picks.pool==='any'?ALLSK:r.picks.pool,r.picks.n,S.raceSk)}</div>`;
  if(D.nExp){ const prof=Object.keys(D.prof); h+=`<div class="plate" style="margin-top:16px"><h3>Expertise</h3><p class="who">Double your proficiency bonus in ${D.nExp} skill${D.nExp>1?'s':''} you are trained in.</p>
    <div class="chips">${prof.map(s=>{ const on=S.exp.includes(s); return `<button class="chip" data-pick="exp" data-v="${esc(s)}" aria-pressed="${on}"${!on&&S.exp.length>=D.nExp?' disabled':''}>${esc(s)}</button>`; }).join('')}</div><p class="count${S.exp.length!==D.nExp?' bad':''}">${S.exp.length} of ${D.nExp} chosen.</p></div>`; }
  h+=`<div class="plate" style="margin-top:16px"><h3>Your skill bonuses</h3><div class="sk">${SKILLS.map(([n,a])=>`<div class="${D.prof[n]?'p':''}"><span>${n} <small>${a}${D.prof[n]===2?', expertise':D.prof[n]?', trained':''}</small></span><b>${sgn(D.skill(n))}</b></div>`).join('')}</div></div>`;
  $('#p-skills').innerHTML=h;
}

/* gear */
function renderGear(){
  const D=calc(), r=race();
  $('#p-gear').innerHTML=`<p class="lede">Choose armor and weapons. Your armor class and attacks are worked out for you.</p>
  <div class="grid g2"><div class="plate"><h3>Armor</h3>
    <div class="fields"><label class="f">Armor${sel('armor',ARMOR.map(a=>[a[0],a[0]+(a[1]==='none'?'':' ('+a[1]+')')]),S.armor)}</label>
    <label class="f">Shield<span><input type="checkbox" data-s="shield" id="f-shield"${S.shield?' checked':''}> Carry a shield (+2)</span></label></div>
    <p style="margin-top:12px">Armor class <b style="color:var(--gold);font-size:1.3rem">${D.ac}</b> <span class="who">${esc(D.acNote)}</span></p>
    ${r&&r.id==='tortle'?'<p class="who">Tortles can\'t wear armor. Their shell gives AC 17.</p>':''}</div>
  <div class="plate"><h3>Weapons</h3><div class="fields">${[0,1,2].map(i=>`<label class="f">Weapon ${i+1}${sel('w.'+i,WEAPONS.map(w=>[w[0],w[0]+' ('+w[2]+')']),S.w[i],'None')}</label>`).join('')}</div>
    ${D.attacks.length?`<div style="margin-top:10px">${D.attacks.map(a=>`<div class="opt"><b>${esc(a.name)}</b> <span class="roll">${esc(a.roll)}</span><p>${esc(a.desc)}</p></div>`).join('')}</div>`:''}</div></div>
  <div class="plate" style="margin-top:16px"><h3>Everything else you carry</h3><label class="f">Packs, tools, treasure, magic items<textarea data-s="gear" id="f-gear" rows="5">${esc(S.gear)}</textarea></label></div>`;
}

/* spells */
let spQ='', spAll=false;
function spellRows(){
  const D=calc(); const list=D.cast?D.cast.list:'', max=D.cast?D.cast.max:9, q=spQ.trim().toLowerCase();
  const xs=SPELLS.filter(x=>(spAll||!list||x.c.includes(list))&&(spAll&&!D.cast?true:x.l<=max)&&(!q||x.n.toLowerCase().includes(q)||x.d.toLowerCase().includes(q)));
  if(!xs.length) return '<p class="who" style="padding:10px 12px;margin:0">No spells match. Clear the search, or add the spell by hand below.</p>';
  let h='', lv=-1;
  xs.forEach(x=>{ if(x.l!==lv){ lv=x.l; h+=`<div class="splv">${lv?ORD[lv]+' level':'Cantrips'}</div>`; }
    h+=`<button class="sp" data-spell="${esc(x.n)}" aria-pressed="${S.picked.includes(x.n)}"><b>${esc(x.n)}</b><small>${esc(TIME[x.t]||x.t)}${x.f.includes('c')?', concentration':''}${x.f.includes('r')?', ritual':''}</small><span>${esc(x.d)}</span></button>`; });
  return h;
}
function spellCount(){ const pk=S.picked.map(n=>SPBY[n]).filter(Boolean); const c0=pk.filter(x=>x.l===0).length; return c0+' cantrip'+(c0===1?'':'s')+' and '+(pk.length-c0)+' spell'+(pk.length-c0===1?'':'s')+' chosen.'; }
function renderSpells(){
  const D=calc(), c=cls();
  $('#p-spells').innerHTML=`<p class="lede">${D.cast?'Pick the spells your character has.':'Your class does not cast spells on its own.'}</p>
  ${D.cast?`<div class="plate"><h3>${c.name} spellcasting</h3>
    <div class="stats"><div class="stat"><b>${D.cast.dc}</b>Spell save DC</div><div class="stat"><b>${sgn(D.cast.atk)}</b>Spell attack</div><div class="stat"><b class="sm">${ABN[D.cast.ab]}</b>Casting ability</div>${D.cast.can?`<div class="stat"><b>${D.cast.can}</b>Cantrips known</div>`:''}</div>
    <p><b>Spell slots.</b> ${esc(D.cast.slots)}.</p>${D.cast.count?`<p>${esc(D.cast.count)}.</p>`:''}</div>`
   :`<div class="plate"><p>${c?'If your subclass, a feat, or an item gives you spells, tick "Show every class" and pick them here.':'Choose a class first.'} You can skip this step.</p></div>`}
  <div class="plate" style="margin-top:16px"><h3>Spell list</h3>
    <div class="fields wide"><label class="f">Search by name or effect<input id="spQ" type="search" autocomplete="off" value="${esc(spQ)}" placeholder="fire, heal, teleport"></label>
    <label class="f">Which spells<span><input type="checkbox" id="spAll"${spAll?' checked':''}> Show every class's spells</span></label></div>
    <p class="count" id="spCount" style="margin:10px 0 8px">${spellCount()}</p>
    <div class="splist" id="spList">${spellRows()}</div>
    <p class="who" style="margin-top:10px">${D.cast?'Showing the '+esc(c.name)+' list up to the highest level you can cast. ':''}The list covers the core rules spells. Descriptions are short summaries, so check your book for the full text.</p>
  </div>
  <details style="margin-top:16px"><summary>Add a spell that is not on the list</summary>
  <div class="grid g2" style="margin-top:8px">
    <label class="f">Extra cantrips, one per line. Add a note after a colon.<textarea data-s="cantrips" id="f-cantrips" rows="5" placeholder="Booming Blade: melee attack plus thunder if the target moves">${esc(S.cantrips)}</textarea></label>
    <label class="f">Extra spells, one per line. Add a note after a colon.<textarea data-s="spells" id="f-spells" rows="5" placeholder="Absorb Elements: reaction, resist the triggering damage">${esc(S.spells)}</textarea></label>
  </div></details>
  <p class="who" style="margin-top:14px">Spell names and class lists come from the System Reference Document 5.1 by Wizards of the Coast, used under the Creative Commons Attribution 4.0 licence.</p>`;
}

/* details */
function renderDetails(){
  $('#p-details').innerHTML=`<p class="lede">Who are they?</p>
  <div class="plate"><div class="fields wide">
    <label class="f">Character name<input data-s="name" id="f-name" value="${esc(S.name)}" autocomplete="off"></label>
    <label class="f">Your name<input data-s="player" id="f-player" value="${esc(S.player)}" autocomplete="off"></label>
    <label class="f">Languages<input data-s="langs" id="f-langs" value="${esc(S.langs)}" autocomplete="off"></label></div></div>
  <div class="grid g2" style="margin-top:16px">
    <div class="plate"><h3>Appearance</h3><label class="f">What people notice first<textarea data-s="look" id="f-look" rows="5">${esc(S.look)}</textarea></label></div>
    <div class="plate"><h3>Story</h3><label class="f">Where they come from and what they want<textarea data-s="story" id="f-story" rows="5">${esc(S.story)}</textarea></label></div></div>
  <div class="plate" style="margin-top:16px"><h3>Subclass features, feats, and anything else</h3>
    <label class="f">One per line, as Name: what it does. These join your list of abilities.<textarea data-s="extras" id="f-extras" rows="6" placeholder="Improved Critical: my weapon attacks crit on a 19 or 20">${esc(S.extras)}</textarea></label></div>
  <div class="plate" style="margin-top:16px"><h3>Combat card</h3><p class="who">Three lines you can act on without reading your whole sheet.</p>
    <div class="fields wide">
    <label class="f">Go-to attack<input data-s="card.go" id="f-card-go" value="${esc(S.card.go)}" autocomplete="off" placeholder="What you do on most turns"></label>
    <label class="f">Signature move<input data-s="card.sig" id="f-card-sig" value="${esc(S.card.sig)}" autocomplete="off" placeholder="The thing your character is known for"></label>
    <label class="f">Emergency button<input data-s="card.emg" id="f-card-emg" value="${esc(S.card.emg)}" autocomplete="off" placeholder="What you do when things go wrong"></label></div></div>`;
}

/* sheet */
function renderSheet(){
  const D=calc(), C=toHub(), r=race(), c=cls(), miss=[];
  if(!r) miss.push('Choose a people.'); else if(!S.p2||!S.p1) miss.push('Choose your +2 and +1 abilities on the People step.');
  if(!c) miss.push('Choose a class.');
  if(S.method==='buy'&&ABS.reduce((t,[k])=>t+(COST[S.base[k]]||0),0)>27) miss.push('Your point buy is over 27 points.');
  if(D.asiSpent>D.asiBudget) miss.push('You have placed more level-up points than you have.');
  if(!S.bg) miss.push('Choose a background on the Skills step.');
  if(c&&S.clsSk.length!==D.nCls) miss.push('Choose '+D.nCls+' class skills.');
  if(S.raceSk.length!==D.nRace) miss.push('Choose your '+(r?r.name:'')+' skills.');
  if(S.exp.length!==D.nExp) miss.push('Choose your Expertise skills.');
  if(!S.name) miss.push('Name your character on the Details step.');
  const cat=k=>C.options.filter(o=>o.cat===k);
  const olist=xs=>xs.map(o=>`<div class="opt"><b>${esc(o.name)}</b>${o.cost!=='Passive'?`<span class="badge">${esc(o.cost)}</span>`:''}${o.max?`<span class="badge">${o.max} use${o.max>1?'s':''}</span>`:''}${o.roll?` <span class="roll">${esc(o.roll)}</span>`:''}${o.desc?`<p>${esc(o.desc)}</p>`:''}</div>`).join('');
  $('#p-sheet').innerHTML=`${miss.length?`<div class="warn"><b>Still to do</b><ul>${miss.map(m=>`<li>${esc(m)}</li>`).join('')}</ul></div>`:''}
  <div class="sheet stack">
    <div class="plate"><h2 style="margin-top:0">${esc(S.name||'Unnamed character')}</h2>
      <p class="lede" style="margin-bottom:4px">Level ${D.L} ${r?esc(r.name):''} ${esc(C.cls)}</p>
      <p class="who">${S.bg?esc(S.bg)+'. ':''}${S.player?'Played by '+esc(S.player)+'.':''}</p>
      <div class="stats"><div class="stat"><b>${D.ac}</b>Armor class</div><div class="stat"><b>${D.hp}</b>Hit points</div><div class="stat"><b class="sm">${esc(D.speed)}</b>Speed</div><div class="stat"><b>${sgn(D.m.dex)}</b>Initiative</div><div class="stat"><b>${sgn(D.pb)}</b>Proficiency</div><div class="stat"><b>${10+D.skill('Perception')}</b>Passive Perception</div><div class="stat"><b class="sm">${D.hd}</b>Hit dice</div><div class="stat"><b>${D.atk}</b>Attacks per action</div></div>
      <div class="stats">${ABS.map(([k,n])=>`<div class="stat"><b>${D.ab[k]}</b>${n}<br>${sgn(D.m[k])} · save ${sgn(D.m[k]+(D.saves[k]?D.pb:0))}${D.saves[k]?' ●':''}</div>`).join('')}</div>
    </div>
    <div class="plate"><h3>Skills</h3><div class="sk">${SKILLS.map(([n,a])=>`<div class="${D.prof[n]?'p':''}"><span>${n} <small>${a}${D.prof[n]===2?', expertise':D.prof[n]?', trained':''}</small></span><b>${sgn(D.skill(n))}</b></div>`).join('')}</div></div>
    ${cat('Attack').length?`<div class="plate"><h3>Attacks</h3>${olist(cat('Attack'))}</div>`:''}
    ${cat('Ability').length?`<div class="plate"><h3>Abilities</h3>${olist(cat('Ability'))}</div>`:''}
    ${cat('Spell').length?`<div class="plate"><h3>Spells</h3>${olist(cat('Spell'))}</div>`:''}
    <div class="grid g2"><div class="plate"><h3>Gear</h3><p class="pre">${esc(C.gear)||'<span class="who">Nothing listed.</span>'}</p></div>
    <div class="plate"><h3>Notes</h3><p class="pre">${esc(C.notes)||'<span class="who">Nothing listed.</span>'}</p></div></div>
    ${(S.card.go||S.card.sig||S.card.emg)?`<div class="plate"><h3>Combat card</h3><p><b>Go-to attack.</b> ${esc(S.card.go)}</p><p><b>Signature move.</b> ${esc(S.card.sig)}</p><p><b>Emergency button.</b> ${esc(S.card.emg)}</p></div>`:''}
    <div class="plate"><h3>Save this character</h3>
      <p>Saving puts this sheet on My character and fills in your Combat page. Your DM sees it too.</p>
      <p><button class="act big" id="saveChar">Save my character</button> <span class="who" id="saveMsg"></span></p>
      <p class="who" style="margin-top:10px">Changed something? Come back to this step and save again. Saving replaces the sheet with the builder's version. Your tier, Spark, Faith, and domain are kept.</p>
      <p style="margin-top:14px"><button class="act quiet" id="reset">Start a new character</button> <span id="resetAsk" hidden>This clears everything here. <button class="act" id="resetYes">Clear it</button> <button class="act quiet" id="resetNo">Keep it</button></span></p>
    </div>
  </div>`;
}

/* combat: the three-line card on the left, every option grouped by what it costs on the right */
let cF='All';
const TYPES=[['Action','Actions'],['Bonus action','Bonus actions'],['Reaction','Reactions'],['Free','Free, alongside something else'],['Passive','Always on']];
function combatList(C){
  const xs=C.options.filter(o=>cF==='All'||o.cost===cF); if(!C.options.length) return '<div class="plate"><p>Your attacks, abilities, and spells appear here once you choose a people and a class.</p></div>';
  if(!xs.length) return '<p class="who">Nothing on your list uses that kind of action.</p>';
  return TYPES.map(([k,label])=>{ const g=xs.filter(o=>o.cost===k); if(!g.length) return '';
    return `<h3 class="cat">${label} <small>${g.length}</small></h3>`+g.map(o=>`<div class="opt"><b>${esc(o.name)}</b><span class="badge">${esc(o.cat)}</span>${o.max?`<span class="badge">${o.max} use${o.max>1?'s':''}</span>`:''}${o.roll?` <span class="roll">${esc(o.roll)}</span>`:''}${o.desc?`<p>${esc(o.desc)}</p>`:''}</div>`).join(''); }).join('');
}
function renderCombat(){
  const D=calc(), C=toHub(), r=race();
  const pills=(label,n)=>Array.from({length:n},(_,i)=>`<button class="pill" aria-pressed="false">${label}${n>1?' '+(i+1):''}</button>`).join('');
  const count=k=>C.options.filter(o=>o.cost===k).length;
  $('#p-combat').innerHTML=`<p class="lede">Your turn at a glance. This same page is under Combat once you save your character.</p>
  <div class="cgrid">
    <aside class="cleft"><div class="plate">
      <h3>${esc(S.name||'Unnamed character')}</h3><p class="who">Level ${D.L} ${r?esc(r.name):''} ${esc(C.cls)}</p>
      <div class="stats c3"><div class="stat"><b>${D.ac}</b>Armor class</div><div class="stat"><b>${D.hp}</b>Hit points</div><div class="stat"><b class="sm">${esc(D.speed.split(',')[0])}</b>Speed</div></div>
      <h4>This turn</h4>
      <p class="who">You get one of each. Select one when you have used it.</p>
      <div class="pills">${pills('Action',1)}${pills('Bonus action',1)}${pills('Reaction',1)}</div>
      <p class="who">Attacks per action <b style="color:var(--vellum)">${D.atk}</b></p>
      <p><button class="act" id="newTurn">Start a new turn</button></p>
      <h4>Combat card</h4>
      <p class="who">Three lines you can act on without reading your whole sheet.</p>
      <label class="f cardline">Go-to attack<input data-s="card.go" id="c-card-go" value="${esc(S.card.go)}" autocomplete="off" placeholder="What you do on most turns"></label>
      <label class="f cardline">Signature move<input data-s="card.sig" id="c-card-sig" value="${esc(S.card.sig)}" autocomplete="off" placeholder="The thing your character is known for"></label>
      <label class="f cardline">Emergency button<input data-s="card.emg" id="c-card-emg" value="${esc(S.card.emg)}" autocomplete="off" placeholder="What you do when things go wrong"></label>
    </div></aside>
    <div>
      <div class="chips" style="margin-top:0">${[['All','Everything',C.options.length]].concat(TYPES.map(t=>[t[0],t[0]==='Free'?'Free':t[0]==='Passive'?'Always on':t[1],count(t[0])])).map(x=>`<button class="chip" data-cf="${x[0]}" aria-pressed="${x[0]===cF}">${x[1]} ${x[2]}</button>`).join('')}</div>
      <div id="cList">${combatList(C)}</div>
    </div>
  </div>`;
}

/* ---------- events ---------- */
function setPath(k,v){ const ps=k.split('.'); const l=ps.pop(); const t=ps.reduce((a,p)=>a[p],S); t[l]=v; }
root.addEventListener('click',e=>{
  const t=e.target.closest('[data-step]'); if(t){ go(+t.dataset.step); window.scrollTo({top:0}); return; }
  const rc=e.target.closest('[data-race]'); if(rc){ if(S.race!==rc.dataset.race){ S.race=rc.dataset.race; S.raceSk=[]; S.anc=''; } persist(); render(); playVid(); return; }
  const cc=e.target.closest('[data-cls]'); if(cc){ if(S.cls!==cc.dataset.cls){ S.cls=cc.dataset.cls; S.sub=''; S.clsSk=[]; S.exp=[]; } persist(); render(); return; }
  const m=e.target.closest('[data-method]'); if(m){ S.method=m.dataset.method; if(S.method==='array'){ ABS.forEach(([k],i)=>{ S.base[k]=ARRAY[i]; }); } if(S.method==='buy'){ ABS.forEach(([k])=>{ S.base[k]=Math.max(8,Math.min(15,parseInt(S.base[k],10)||8)); }); } persist(); render(); return; }
  const pill=e.target.closest('.pill'); if(pill){ pill.setAttribute('aria-pressed',pill.getAttribute('aria-pressed')!=='true'); return; }
  if(e.target.id==='newTurn'){ root.querySelectorAll('#p-combat .pill').forEach(p=>p.setAttribute('aria-pressed','false')); return; }
  const cf=e.target.closest('[data-cf]'); if(cf){ cF=cf.dataset.cf; root.querySelectorAll('[data-cf]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.cf===cF)); $('#cList').innerHTML=combatList(toHub()); return; }
  const spb=e.target.closest('[data-spell]'); if(spb){ const n=spb.dataset.spell, i=S.picked.indexOf(n); if(i>=0) S.picked.splice(i,1); else S.picked.push(n); spb.setAttribute('aria-pressed',i<0); $('#spCount').textContent=spellCount(); persist(); return; }
  const pk=e.target.closest('[data-pick]'); if(pk&&!pk.disabled){ const a=S[pk.dataset.pick], v=pk.dataset.v, i=a.indexOf(v); if(i>=0) a.splice(i,1); else a.push(v);
    S.exp=S.exp.filter(s=>calc().prof[s]); persist(); render(); return; }
  if(e.target.id==='prev'){ go(step_-1); window.scrollTo({top:0}); return; }
  if(e.target.id==='next'){ go(step_+1); window.scrollTo({top:0}); return; }
  if(e.target.id==='rvBtn'){ const v=$('#rv'); if(v.paused){ v.play(); e.target.textContent='Pause'; } else { v.pause(); e.target.textContent='Play'; } return; }
  if(e.target.id==='saveChar'){ const msg=$('#saveMsg'); msg.textContent='Saving…'; opts.finish(toHub(),S).then(()=>{ msg.innerHTML='Saved. <a href="'+esc(opts.sheetHref)+'">Open My character</a>'; },()=>{ msg.textContent='That did not save. Try again in a moment.'; }); return; }
  if(e.target.id==='reset'){ $('#resetAsk').hidden=false; return; }
  if(e.target.id==='resetNo'){ $('#resetAsk').hidden=true; return; }
  if(e.target.id==='resetYes'){ S=blank(); vidKey=''; persist(); const v=$('#rv'); v.removeAttribute('src'); v.removeAttribute('poster'); v.load(); $('#rvHint').hidden=false; $('#rvBtn').hidden=true; go(0); window.scrollTo({top:0}); return; }
});
function onField(e,commit){ const el=e.target, k=el.dataset&&el.dataset.s; if(!k) return;
  let v=el.type==='checkbox'?el.checked:el.value; if(el.hasAttribute('data-num')||/^base\./.test(k)||k==='level') v=v===''?'':Number(v);
  if(/^base\./.test(k)&&S.method==='array'){ const me=k.slice(5), old=S.base[me]; const other=ABS.map(a=>a[0]).find(x=>x!==me&&S.base[x]===v); if(other) S.base[other]=old; }
  setPath(k,v);
  if(k==='p2'&&S.p1===S.p2) S.p1='';
  if(k==='bg') S.bgSk=[];
  if(k==='bg'||k==='level'){ const tk=new Set(calc().bgSk); S.clsSk=S.clsSk.filter(s=>!tk.has(s)); S.raceSk=S.raceSk.filter(s=>!tk.has(s)); const D=calc(); S.exp=S.exp.filter(s=>D.prof[s]).slice(0,D.nExp); }
  persist();
  if(commit&&(el.tagName==='SELECT'||el.type==='checkbox'||el.type==='number')) render(); else renderTabs(); }
root.addEventListener('input',e=>{ if(e.target.id==='spQ'){ spQ=e.target.value; $('#spList').innerHTML=spellRows(); return; } onField(e,false); });
root.addEventListener('change',e=>{ if(e.target.id==='spAll'){ spAll=e.target.checked; $('#spList').innerHTML=spellRows(); return; } if(e.target.id==='spQ') return; onField(e,true); });

/* ---------- start ---------- */
try{ step_=Math.max(0,Math.min(8,parseInt(sessionStorage.getItem('dbb-builder-step'),10)||0)); }catch(e){}
go(step_);
return ()=>{ const v=$('#rv'); if(v) v.pause(); };
}
