// GENERATED by scripts/build-islands.mjs from source/session-negative-run-sheet/index.html. Do not edit by hand.
/* eslint-disable */
// @ts-nocheck
export function mountRunSheet(root, opts){
const $ = s => root.querySelector(s);
const STATE = Object.assign({}, opts.state || {});
const store = { get(k,d){ return STATE[k] == null ? d : JSON.parse(JSON.stringify(STATE[k])); }, set(k,v){ STATE[k] = v; opts.save(STATE); } };
const T = opts.content.trackers;
const num = v => { const n = parseInt(v,10); return isNaN(n) ? 0 : n; };

/* shared blocks used in both fights */
['#hostMoves','#hostMoves2'].forEach(s => $(s).append($('#tHost').content.cloneNode(true)));
['#dropRule','#dropRule2'].forEach(s => $(s).append($('#tDrop').content.cloneNode(true)));

/* beats */
const ORDER = opts.content.order;
function show(id, scroll){
  if(!root.querySelector('#' + CSS.escape(id))) id = ORDER[0];
  root.querySelectorAll('[role=tabpanel]').forEach(p => p.hidden = p.id !== id);
  root.querySelectorAll('.step').forEach(b => b.setAttribute('aria-selected', b.dataset.p === id));
  const i = ORDER.indexOf(id);
  $('#prev').hidden = i <= 0; $('#next').hidden = i < 0 || i === ORDER.length-1;
  if(i > 0) $('#prev').textContent = 'Back: ' + $('.step[data-p="'+ORDER[i-1]+'"]').textContent.replace(/^\d/,'');
  if(i >= 0 && i < ORDER.length-1) $('#next').textContent = 'Next: ' + $('.step[data-p="'+ORDER[i+1]+'"]').textContent.replace(/^\d/,'');
  store.set('beat', id);
  const cur = $('.step[aria-selected="true"]'); if(cur && cur.scrollIntoView) cur.scrollIntoView({block:'nearest', inline:'nearest'});
  if(scroll) window.scrollTo({top:0});
}
root.querySelectorAll('.step').forEach(b => b.addEventListener('click', () => show(b.dataset.p, true)));
root.addEventListener('click', e => { const g = e.target.closest('[data-goto]'); if(g) show(g.dataset.goto, true); });
$('#prev').addEventListener('click', () => show(ORDER[ORDER.indexOf(store.get('beat', ORDER[0]))-1], true));
$('#next').addEventListener('click', () => show(ORDER[ORDER.indexOf(store.get('beat', ORDER[0]))+1], true));

/* the Host */
const hostEl = $('#host');
function setHost(n){ n = Math.max(0, n); hostEl.value = n; store.set('host', n);
  root.querySelectorAll('.hostNow').forEach(e => e.textContent = n);
  $('#hostDmg').textContent = Math.floor(n/2); }
hostEl.addEventListener('input', () => setHost(num(hostEl.value)));
root.addEventListener('click', e => { const b = e.target.closest('[data-host]'); if(b) setHost(num(hostEl.value) + num(b.dataset.host)); });
$('#gaze').addEventListener('click', () => setHost(num(hostEl.value) - T.gaze));

/* dragons */
const D0 = T.dragons;
let D = store.get('dragons', null) || JSON.parse(JSON.stringify(D0));
let dRound = store.get('dRound', 1);
function drawDragons(){
  $('#dragons').innerHTML = D.map((d,i) => `<div class="trow${d.hp<=0?' down':''}"><span><b>${d.n}</b><small>${d.t}</small></span>
    <label class="meta"><input type="checkbox" id="dp${i}" data-i="${i}" ${d.p?'checked':''}> on party</label>
    <input type="number" id="dh${i}" data-i="${i}" min="0" max="178" value="${d.hp}" aria-label="${d.n} hit points"></div>`).join('');
  dragonSummary();
}
function dragonSummary(){
  const on = D.filter(d => d.hp > 0 && !d.p).length;
  $('#dOnHost').textContent = on;
  $('#dLoss').textContent = on ? Array(on).fill('2d4').join(' + ') : 'nobody';
  $('#dRound').textContent = dRound;
  root.querySelectorAll('#dragons .trow').forEach((r,i) => r.classList.toggle('down', D[i].hp <= 0));
  store.set('dragons', D); store.set('dRound', dRound);
}
$('#dragons').addEventListener('input', e => { const i = e.target.dataset.i; if(i == null) return;
  if(e.target.type === 'checkbox') D[i].p = e.target.checked; else D[i].hp = Math.max(0, num(e.target.value));
  dragonSummary(); });
$('#dNext').addEventListener('click', () => { dRound++; dragonSummary(); });
$('#dReset').addEventListener('click', () => { D = JSON.parse(JSON.stringify(D0)); dRound = 1; drawDragons(); });

/* Voth */
let V = store.get('voth', Object.assign({}, T.voth));
function drawVoth(){
  const per = T.perPhase[V.party] || T.perPhase[T.voth.party], max = per*3, hp = Math.max(0, max - V.dmg);
  $('#party').value = V.party; $('#perPhase').textContent = per; $('#vMax').textContent = max;
  $('#vHp').textContent = hp > 0 ? hp : 'Dead'; $('#vRound').textContent = V.round;
  const ph = hp <= 0 ? -1 : hp > per*2 ? 0 : hp > per ? 1 : 2;
  $('#phase').querySelectorAll('span').forEach((s,i) => s.classList.toggle('on', i === ph));
  store.set('voth', V);
}
$('#party').addEventListener('change', e => { V.party = num(e.target.value); drawVoth(); });
$('#vHit').addEventListener('click', () => { const a = Math.max(0, num($('#vDmg').value)); if(!a){ $('#vDmg').focus(); return; } V.dmg += a; $('#vDmg').value = ''; drawVoth(); });
$('#vDmg').addEventListener('keydown', e => { if(e.key === 'Enter') $('#vHit').click(); });
$('#hostHit').addEventListener('click', () => { V.dmg += Math.floor(num(hostEl.value)/2); drawVoth(); });
$('#vNext').addEventListener('click', () => { V.round++; drawVoth(); });
$('#vReset').addEventListener('click', () => { V.dmg = 0; V.round = 1; ['#ls1','#ls2','#ls3'].forEach(s => $(s).checked = false); drawVoth(); });

/* start */
drawDragons(); drawVoth(); setHost(store.get('host', T.host));
show(store.get('beat', ORDER[0]), false);
}
