// Lifts the character builder's and the run sheet's scripts out of source/ and adapts
// them to this app, so their behaviour stays exactly as written. Each change below is a
// named patch; the script fails loudly if the source no longer matches a patch.
//
// What changes, and only this:
//   - rules data and tracker defaults come from the database (opts), not constants in the file
//   - saving goes to the database through callbacks, not localStorage or window.claude
//   - media comes from the signed-URL route, not relative t/ and v/ paths
//   - the "copy a character code" step becomes "Save my character"
//   - the DM's phase switch is removed here (it lives on the Manage page)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(ROOT, 'source', p), 'utf8');
const scriptOf = (html) => html.slice(html.lastIndexOf('<script>') + 8, html.lastIndexOf('</script>'));

function patcher(code) {
  return {
    get code() { return code; },
    rep(label, from, to) {
      const before = code;
      code = typeof from === 'string' ? code.split(from).join(to) : code.replace(from, to);
      if (code === before) throw new Error('patch did not apply: ' + label);
      return this;
    },
  };
}

// ------------------------------------------------------------------ builder

{
  const html = read('character-builder/index.html');
  const js = scriptOf(html);
  const stepLine = js.match(/const od=n=>n; const step=.*\n/)[0];
  const p = patcher(js.slice(js.indexOf('/* ---------- state ---------- */')));

  p.rep('phase from the campaign', "let S=blank(), PHASE='before', step_=0;", "let S=blank(), PHASE=opts.phase==='after'?'after':'before', step_=0;")
    .rep('load draft from the database', "const raw=localStorage.getItem('tbg-builder'); if(raw){ const o=JSON.parse(raw);", 'const o=opts.state; if(o){')
    .rep('persist draft to the database', /function persist\(\)\{[^\n]*\n/, 'function persist(){ opts.persist(S); }\n')
    .rep('default level from phase config', "(PHASE==='before'?15:1)", '(CFG.defaultLevel||1)')
    .rep('divine vitality from phase config', "(PHASE==='after'?Math.floor(D.ab.con/2):0)", '(CFG.vitality?Math.floor(D.ab.con/2):0)')
    .rep('level note from phase config', "${PHASE==='before'?'Your DM is running the opening one-shot at level 15.':'The campaign starts at level 1.'}", "${esc(CFG.levelNote||'')}")
    .rep('remember step for this visit', "try{ localStorage.setItem('tbg-builder-step',String(step_)); }catch(e){}", "try{ sessionStorage.setItem('dbb-builder-step',String(step_)); }catch(e){}")
    .rep('restore step', "localStorage.getItem('tbg-builder-step')", "sessionStorage.getItem('dbb-builder-step')")
    .rep('video through the media route', "const base='v/'+r.vid+(r.two?'_'+PHASE:'');", "const base=opts.media+'/v/'+r.vid;")
    .rep('portraits through the media route', '<img src="t/${r.vid}.jpg"', '<img src="${opts.media}/t/${r.vid}.jpg"')
    .rep('save instead of copying a code',
      /<div class="plate"><h3>Send this sheet to the player guide and your DM<\/h3>[\s\S]*?copy a fresh code\.<\/p>/,
      `<div class="plate"><h3>Save this character</h3>
      <p>Saving puts this sheet on My character and fills in your Combat page. Your DM sees it too.</p>
      <p><button class="act big" id="saveChar">Save my character</button> <span class="who" id="saveMsg"></span></p>
      <p class="who" style="margin-top:10px">Changed something? Come back to this step and save again. Saving replaces the sheet with the builder's version. Your tier, Spark, Faith, and domain are kept.</p>`)
    .rep('save handler',
      /if\(e\.target\.id==='copy'\)\{[\s\S]*?catch\(err\)\{ fail\(\); \} return; \}/,
      "if(e.target.id==='saveChar'){ const msg=$('#saveMsg'); msg.textContent='Saving…'; opts.finish(toHub(),S).then(()=>{ msg.innerHTML='Saved. <a href=\"'+esc(opts.sheetHref)+'\">Open My character</a>'; },()=>{ msg.textContent='That did not save. Try again in a moment.'; }); return; }")
    .rep('combat lede', 'This same page is in the player guide once you import your code.', 'This same page is under Combat once you save your character.')
    .rep('no phase switch here (click)', "  const ph=e.target.closest('[data-phase]'); if(ph) setPhase(ph.dataset.phase);\n", '')
    .rep('no phase switch here (block)', /\/\* ---------- which videos players see[\s\S]*?(?=\/\* ---------- start ---------- \*\/)/, '')
    .rep('events on the island root', /document\.addEventListener\(/g, 'root.addEventListener(')
    .rep('queries on the island root', /document\.querySelectorAll\(/g, 'root.querySelectorAll(');

  if (/localStorage|window\.claude|document\./.test(p.code)) throw new Error('builder: host-specific code left behind');

  const out = `// GENERATED by scripts/build-islands.mjs from source/character-builder/index.html. Do not edit by hand.
/* eslint-disable */
// @ts-nocheck
import { esc, sgn, ABS, SKILLS } from './character';

${stepLine.trim()}

// Rules rows store functions as {"$fn": "source"}. Only the DM can write rules rows.
export function revive(v){
  if(Array.isArray(v)) return v.map(revive);
  if(v&&typeof v==='object'){ if(typeof v.$fn==='string') return new Function('step','sgn','return ('+v.$fn+')')(step,sgn); const o={}; for(const k in v) o[k]=revive(v[k]); return o; }
  return v;
}

export function mountBuilder(root, opts){
const $=s=>root.querySelector(s);
const ABN=Object.fromEntries(ABS);
const ALLSK=SKILLS.map(s=>s[0]);
const amod=v=>Math.floor((v-10)/2);
const {RACES,CLASSES,FULL,PACT,ORD,BGS,ARMOR,WEAPONS,SPELLS,ANCESTRY,TIME,COST,ARRAY}=revive(opts.rules);
const CFG=opts.phaseConfig||{};
const SPBY=Object.fromEntries(SPELLS.map(x=>[x.n,x]));

${p.code.trim()}
return ()=>{ const v=$('#rv'); if(v) v.pause(); };
}
`;
  fs.writeFileSync(path.join(ROOT, 'src', 'islands', 'builder.gen.js'), out);

  // the builder's static markup: step tabs, the people stage, empty step panels, back and next
  let body = html.slice(html.indexOf('</style>') + 8, html.indexOf('<script>')).trim();
  const bp = patcher(body);
  bp.rep('drop the DM box', /\s*<div class="plate" id="dmBox"[\s\S]*?id="dmMsg"><\/p>\s*<\/div>/, '')
    .rep('save state text', 'Your progress saves in this browser as you go.', 'Your progress saves to your account as you go.');
  fs.writeFileSync(path.join(ROOT, 'src', 'islands', 'builder.html.js'),
    `// GENERATED by scripts/build-islands.mjs from source/character-builder/index.html. Do not edit by hand.\nexport const BUILDER_HTML = ${JSON.stringify(bp.code)};\n`);
}

// ------------------------------------------------------------------ run sheet

{
  const js = scriptOf(read('session-negative-run-sheet/index.html'));
  const p = patcher(js);
  p.rep('root-scoped $', 'const $ = s => document.querySelector(s);', 'const $ = s => root.querySelector(s);')
    .rep('state in the database', /const store = \{[\s\S]*?\} \};\n/, "const STATE = Object.assign({}, opts.state || {});\nconst store = { get(k,d){ return STATE[k] == null ? d : JSON.parse(JSON.stringify(STATE[k])); }, set(k,v){ STATE[k] = v; opts.save(STATE); } };\nconst T = opts.content.trackers;\n")
    .rep('beat order from the database', /const ORDER = \[[^\]]*\];/, 'const ORDER = opts.content.order;')
    .rep('first beat', "if(!document.getElementById(id)) id = 'muster';", "if(!root.querySelector('#' + CSS.escape(id))) id = ORDER[0];")
    .rep('default beat', /store\.get\('beat', ?'muster'\)/g, "store.get('beat', ORDER[0])")
    .rep('gaze from the database', "setHost(num(hostEl.value) - 50)", 'setHost(num(hostEl.value) - T.gaze)')
    .rep('dragons from the database', /const D0 = \[[^\n]*\];/, 'const D0 = T.dragons;')
    .rep('voth defaults from the database', "store.get('voth', {party:5, dmg:0, round:1})", "store.get('voth', Object.assign({}, T.voth))")
    .rep('phase hit points from the database', '{4:300, 5:350, 6:400}[V.party] || 350', 'T.perPhase[V.party] || T.perPhase[T.voth.party]')
    .rep('host default from the database', "store.get('host', 200)", "store.get('host', T.host)")
    .rep('no location hash', "show((location.hash || '').slice(1) || store.get('beat', ORDER[0]), false);", "show(store.get('beat', ORDER[0]), false);")
    .rep('events on the island root', /document\.addEventListener\(/g, 'root.addEventListener(')
    .rep('queries on the island root', /document\.querySelectorAll\(/g, 'root.querySelectorAll(');
  if (/localStorage|document\./.test(p.code)) throw new Error('run sheet: host-specific code left behind');
  fs.writeFileSync(path.join(ROOT, 'src', 'islands', 'runsheet.gen.js'),
    `// GENERATED by scripts/build-islands.mjs from source/session-negative-run-sheet/index.html. Do not edit by hand.\n/* eslint-disable */\n// @ts-nocheck\nexport function mountRunSheet(root, opts){\n${p.code.trim()}\n}\n`);
}

console.log('wrote builder.gen.js, builder.html.js, runsheet.gen.js');
