// Lifts the stylesheets out of the source sites and scopes each one under a class,
// so the campaign look never leaks into the hub shell and the three source designs
// (guide/hub, builder, run sheet) never fight each other.
//
// Colours are rewritten to the campaign's tokens (var(--gold) and so on) so that a
// different theme in campaigns.theme restyles everything. With the "To be a god"
// tokens the result is identical to the source.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const styleOf = (p) => { const h = fs.readFileSync(path.join(ROOT, 'source', p), 'utf8'); return h.slice(h.indexOf('<style>') + 7, h.indexOf('</style>')); };

const RGB = { '200,164,90': 'gold', '224,103,47': 'ember', '111,179,160': 'verd', '143,167,214': 'star', '7,9,20': 'void', '12,16,32': 'deep', '20,26,51': 'plate2' };
const HEX = { '#1a1405': 'var(--on-gold)', '#e3c47f': 'var(--gold-hi)', '#b58f45': 'var(--gold-lo)', '#0a0d1c': 'var(--field)' };

// remove a whole rule (selector { ... }) starting at the first match of `re`
function dropRule(css, re) {
  for (;;) {
    const m = css.match(re);
    if (!m) return css;
    let i = css.indexOf('{', m.index), depth = 0;
    for (; i < css.length; i++) { if (css[i] === '{') depth++; else if (css[i] === '}' && --depth === 0) break; }
    css = css.slice(0, m.index) + css.slice(i + 1);
  }
}

function lift(css) {
  css = dropRule(css, /:root\{/);
  css = dropRule(css, /@media \(prefers-color-scheme: dark\)\{/);
  css = dropRule(css, /:root\[data-theme="dark"\]\{/);
  css = dropRule(css, /(^|\n)html\{/);
  css = dropRule(css, /(^|\n)body\{/);                 // page background lives on .campaign (campaign.css)
  css = css.replace(/body\.veiled /g, '&.veiled ').replace(/([\s{;])body\{/g, '$1&{');
  css = css.replace(/rgba\((\d+),(\d+),(\d+),(\.?[\d.]+)\)/g, (all, r, g, b, a) => {
    const t = RGB[`${r},${g},${b}`];
    return t ? `color-mix(in srgb, var(--${t}) ${Math.round(parseFloat(a) * 100)}%, transparent)` : all;
  });
  Object.entries(HEX).forEach(([h, v]) => { css = css.split(h).join(v); });
  const keyframes = [];
  css = css.replace(/@keyframes [^{]+\{(?:[^{}]*\{[^{}]*\})*[^{}]*\}/g, (k) => { keyframes.push(k); return ''; });
  return { css: css.trim(), keyframes };
}

function scope(cls, sheets, extra = '') {
  const parts = sheets.map(lift);
  return `/* Generated by scripts/build-css.mjs from source/. Do not edit by hand. */\n` +
    parts.flatMap((p) => p.keyframes).join('\n') + `\n.${cls}{\n${extra}\n${parts.map((p) => p.css).join('\n')}\n}\n`;
}

const out = path.join(ROOT, 'src', 'styles');
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, 'guide.css'), scope('cs-guide', [styleOf('player-guide/index.html'), styleOf('dm-hub/index.html')], '&{box-sizing:border-box}'));
fs.writeFileSync(path.join(out, 'builder.css'), scope('cs-builder', [styleOf('character-builder/index.html')], '&{box-sizing:border-box; line-height:1.6}'));
fs.writeFileSync(path.join(out, 'runsheet.css'), scope('cs-run', [styleOf('session-negative-run-sheet/index.html')], '&{line-height:1.55}'));
console.log('wrote guide.css, builder.css, runsheet.css');
